---
title: "WHO Life Expectancy Data"
author: "We R Who We R"
date: '2022-07-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
```


``` {r load}
who <- read.csv("who_life_exp.csv")
```

```{r}
 mylabels <- c("Healthy Weight", "Overweight", "Obesity")

who <- who %>%
  mutate(bmi_cat = cut(bmi, breaks = c(18, 24.9, 29.9, Inf), labels = mylabels))
  
```


``` {r glimpe}
glimpse(who)
```

``` {r summary}
summary(who)
```

```{r select}
who %>%
  filter(region == "Europe") %>%
  group_by(country) %>%
  summarize(
    mean_gdi = mean(gni_capita, na.rm = TRUE)) %>%
  slice_max(mean_gdi, n = 5)
```

```{r stats}
who %>%
  filter(region == "Americas" & year == 2016) %>%
  distinct(country)
```

```{r stats2}
who %>%
  group_by(region) %>%
  summarize(min_life = min(life_expect),
            max_life = max(life_expect))

```
  
```{r gni-capita-life-exp}
ggplot(who, mapping = 
         aes(x = gni_capita,
             y = life_expect,
             color = region)) +
  geom_point() +
  facet_wrap(~region)

```


```{r time-life-exp}
ggplot(who, mapping = 
         aes(x = year,
             y = life_expect,
             color = region)) +
  geom_point() +
  facet_wrap(~region)

```

```{r life-exp-childhood-obesity}
who %>%
  filter(region == "Africa") %>%
  ggplot(mapping = 
         aes(x = age5.19obesity,
             y = life_expect,
             color = year)) +
  geom_point() +
  facet_wrap(~region)
```


```{r life-exp-childhood-thin}
who %>%
  filter(region == "Africa") %>%
  ggplot(mapping = 
         aes(x = age5.19thinness,
             y = life_expect,
             color = year)) +
  geom_point() +
  facet_wrap(~region)
```

```{r}
who_USA <- who %>%
  filter(region == "Americas" &
           adult_mortality > 600)

who %>%
  ggplot(mapping = 
         aes(x = adult_mortality,
             y = life_expect)) +
  geom_point(alpha = 0.3) +
  geom_point(data = who_USA,
             aes(x = adult_mortality,
                 y = life_expect,
                 color = year,
                 shape = country))
```

```{r}
who %>%
  filter(country == "Haiti") %>%
  summary()
```

